### PR TITLE
feat: add ability to replace original in conversion

### LINKED ISSUE #1526: How to optimize and replace the original image when uploading to media?
On the $post,there will be request featured containing image of the post,
i have used conversion to create the thumb of the image but i want to optimize the image also original one.
i am using
`$post->addMediaFromRequest('featured')->toMediaCollection('featured');`
Where on the Post model
` $this->addMediaConversion('thumb')
            ->width(env('THUMB_WIDTH',150))
            ->height(env('THUMB_HEIGHT',150))
            ->performOnCollections('featured');`

I find the thumb image is being optimized but not original one.
I could not even find on the documentation too.

### PR DESCRIPTION
**Pull request by Tofandel**
This is a simple feature to allow conversions to be performed on the original image

Fixes #1526

### CODE REVIEW

**Comment by freekmurze** [comment]
Thank you for your work on this, but I'm going to pass.

The philosophy behind media library is that we never touch the original image. Any changes to an image should be done before adding it to the media library. Our image and image optimizer packages allow for easy manipulation of any image.

**Comment by Tofandel** [comment]
Well that's a bit problematic because the media library basically creates this image if you import it from a url or a string, so how are we supposed to optimize it before that, except by reinventing the whole downloader logic?

**Comment by michaellindahl** [comment]
I would definitely agree that this adds value and I've run into a situation where I've needed to do this as well. However, I also understand that this could add complexity to the media library package. We'd want to make sure that re-running media conversions didn't cause this to be re-ran on the original image. 

At first my solution involved copying the logic from [`DefaultDownloader`](https://github.com/spatie/laravel-medialibrary/blob/main/src/Downloaders/DefaultDownloader.php) to download the file.
But with the help of [`invade`](https://github.com/spatie/invade) we can intercept the image prior to handing it off to the media library:

```php
/** @var \Spatie\MediaLibrary\MediaCollections\FileAdder */
$fileAdder = $this->addMediaFromUrl($url);
$filePath = invade($fileAdder)->pathToFile;

/** @var \Spatie\Image\Image */
$image = Image::load($filePath);
$image->optimize();
$image->save();

/** @var \Spatie\MediaLibrary\MediaCollections\Models\Media */
$media = $fileAdder->toMediaCollection();
```

**Comment by Tofandel** [comment]
I do agree, as is, this PR doesn't have the best design, I'm thinking we can either filter the conversions based on the flag and run this on the tmp file before it's even added in the media library

Or add a different method to add manipulations (to differentiate from conversions) so we don't need to filter at all. It can still use the conversion class under the hood for its perfect Api (or extend it)

With this design the original would never make it to the final file system and only the manipulated image and we're sure the conversion will run only once

@freekmurze would you be willing to add this feature with a better  cleaned up design?

**Comment by Tofandel** [comment]
Thanks for the suggestion with invade, will use as a dev workaround

While it may do in a testing environnement, it's really not something I would ship to production as that means accessing private variables which are not prone to breaking changes requirements

So at the very least some events are needed in the library (I would say around [there](https://github.com/spatie/laravel-medialibrary/blob/main/src/MediaCollections/FileAdder.php#L446)) if we want just a chance at implementing optimization

I'm a big fighter for this as disk space is a big way to reduce CO2 emissions (between the multiple drives, the backups, backups of backups and cpu usage of those as well as network load) and this library just doesn't make it easy

**Comment by Tofandel** [comment]
@freekmurze Any new thoughts? This is clearly something the users of the lib want

Should we go with an event or a better design of the feature?

**Comment by ipontt-neering** [comment]
Since this is "so easy" but no examples are available, here's an example.
```php
$file = request()->file('image');

Image::load($file)->format('webp')->save($file->getRealPath());

$media = $model->addMediaFromRequest('image')
        ->usingFileName(pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME). '.webp')
        ->toMediaCollection('image');
```

**Pull request closed without merging**
