### PR TITLE
use Laravel built in bootTraits to perform deletion callback

### LINKED ISSUE #67: Trait delete method conflict
>Trait method delete has not been applied, because there are collisions with other trait methods

Conflicting with `EntityTrait` in https://cartalyst.com/manual/attributes/1.0 package.

### PR DESCRIPTION
**Pull request by uyab**
This also fix #67

### CODE REVIEW

**Comment by freekmurze** [comment]
The tests are failing. Could you fix that?

**Comment by uyab** [comment]
Test failed when using --prefer-lowest, caused by following issue: https://github.com/danielstjules/Stringy/issues/69

**Comment by freekmurze** [comment]
I'm going to leave this for now. Upping the dependancies is considered a breaking change and I'm not ready for a new major version. I'll fix this when tagging a new major version in future.

**Comment by uyab** [comment]
Just curious, why use --prefer-lowest ?

**Comment by freekmurze** [comment]
Here is some background info: http://evertpot.com/testing-composer-prefer-lowest/

**Pull request closed without merging**
