### PR TITLE
lower and space

### PR DESCRIPTION
**Pull request by bmichotte**
This PR change the `sanitizeFileName`. No more `This%20Image.PNG` in our media folders :)

* it replaces spaces with `-`
* it lower case the filename

Test has been changed with this PR

### CODE REVIEW

**Comment by freekmurze** [comment]
Although it isn't a breaking change per sé, it might be unwanted behaviour for some users. I'll add this in the next major version of the package (ETA: early-mid 2017)

**Comment by bmichotte** [comment]
Ok, make sense.
Wwhat about adding a new method then ?

```php
$item->addMediaFromRequest('image')
     ->sanitizingFileName(function($fileName) {
         return strtolower(str_replace(['#', '/', '\\', ' '], '-', $fileName));
     })
     ->toMediaCollection();
```

**Comment by freekmurze** [comment]
That seems pretty nice. Send a PR with tests.

**Comment by freekmurze** [comment]
You'll be happy to know that these changes are now the `v7` branches, which will be released early next year.

**Pull request closed without merging**
