### PR TITLE
Add Laravel 7 support

### PR DESCRIPTION
**Pull request by driesvints**
I needed to work around a `json_decode` call in a model observer. Something seems to have changed here in the new major version but I'm not sure what's caused it 🤔

### CODE REVIEW

**Comment by driesvints** [comment]
Not really sure why scrutinizer is failing. It's complaining about `composer.lock` not being present but that doesn't seems wanted.

**Comment by driesvints** [comment]
Github actions also aren't running for some reason.

**Comment by driesvints** [comment]
I think this PR is the one that affects this: https://github.com/laravel/framework/pull/30273

The current json call is actually a workaround imo so this seems to be fixed/improved for Laravel 7.

**Comment by freekmurze** [comment]
Thanks!

**Comment by freekmurze** [comment]
Refactored it a bit for readability.

**Pull request merged**
