### PR TITLE
Support for custom Media Eloquent model

### PR DESCRIPTION
**Pull request by pascalbaljet**

### CODE REVIEW

**Comment by freekmurze** [comment]
Unless you present a convincing use case, I'm not going to merge this PR. Are you missing certains methods on Media?

**Comment by pascalbaljet** [comment]
The primary reason I want this is to have relations between the Media model and other models. For example, I want to know who uploaded the media, so I now have a relationship with a User model.

**Comment by freekmurze** [comment]
That's a good example. I've decided to accept your PR. Could you rebase it first? Then I'll merge your changes, do a little bit of housekeeping and tag a new version.

Thanks!

**Comment by uyab** [comment]
HI @pascalbaljet, if you have relationship between Media and User model, did you add additional column to media table (something like user_id or uploader_id) ?

**Comment by freekmurze** [comment]
@pascalbaljet I found a bit of time to review your changes and solved the merge conflicts myself. All changes are available in the newly tagged version 3.4.0. Thank you very much for your contribution.

@uyab If you're going to use a custom model and want to use extra field, you should write a migration to add fields (given that you're using the media table provided by this package as a base)

**Comment by uyab** [comment]
Several type hint in HasMediaTrait are still pointing to Model. If I completely can use custom Model, there is a chance that I create the media model from scratch (not extend built in Media). So this will cause an error. What do you think @freekmurze ?

**Comment by freekmurze** [comment]
Are you referring to the `Media` type hints in the closures?

**Comment by uyab** [comment]
Yes

**Comment by freekmurze** [comment]
I've removed the typehints. Unless you need this quickly, these change will get tagged the next time I'll update the package in a more meaningful way.

**Pull request merged**
