### PR TITLE
Fix issue - S3 Responsive Image URL Generator not using root

### PR DESCRIPTION
**Pull request by gtapps**
Appended root to ResponsiveImagesDirectoryUrl function just like the getUrl function.

Cheers,
Gabriel

### CODE REVIEW

**Comment by ragingdave** [comment]
@gtapps any chance you are going to fix the issues outlined and then this could get merged? just found out , I'm in great need of this to work :)

**Comment by freekmurze** [comment]
Thanks!

**Comment by brendt** [comment]
This PR breaks some tests. More specifically https://github.com/spatie/laravel-medialibrary/commit/c40d6192aed141cae292a084358ed6162e450dcb#diff-d7b047ed3b8565f469ac13b3d01449c8R131

There's no method `Media::getResponsiveImagesDirectoryUrl()` according to the failing tests. @gtapps care to take a look at it?

**Comment by daniel-werner** [comment]
Hi @brendt ,

I think I've fixed this, but cannot be sure, as I don't have AWS credentials, so the S3 tests are skipped for me locally. Please find my commit here: https://github.com/daniel-werner/laravel-medialibrary/commit/109514e3fea8c20ebe178933d6e84a2d51bb24c6

**Comment by brendt** [comment]
I believe @riasvdv fixed it here: https://github.com/spatie/laravel-medialibrary/commit/6006af34f95070f9838837066739b58cbeae8236

**Comment by daniel-werner** [comment]
Ahh, ok cool!

**Pull request merged**
