### PR TITLE
Feature/path strategy

### PR DESCRIPTION
**Pull request by cviebrock**
This PR is a solution for #94.

It takes the logic for building paths and URLs and extracts it into it's own class.  You can then use a custom PathGenerator class to save files to directories like:

```
/62/93/62933a2951ef01f4eafd9bdf4d3cd2f0/file.jpg
```

instead of:

```
/1/file.jpg
```

### CODE REVIEW

**Comment by freekmurze** [comment]
Epic pull request, thanks! 

On first glance, there aren't any breaking changes. I'll tag a new version containing these changes soon.

**Comment by dambridge** [comment]
Huge! I know I'm pulling from dev-master atm, but what would a custom class look like to use the PathGenerator?

**Comment by freekmurze** [comment]
Take a look at [this example in the tests](https://github.com/spatie/laravel-medialibrary/blob/master/tests/PathGenerator/CustomPathGenerator.php).

**Comment by freekmurze** [comment]
These changes are available in v3.9.0

**Comment by dambridge** [comment]
Ah, many thanks!

**Comment by alexglue** [comment]
@cviebrock , @freekmurze And why don't you rename the original filename to something like hash-looked-like? 
I want to get files named like "Мой крутой файл лол.jpg", it could make a lot of troubles with that.

**Comment by freekmurze** [comment]
You can set the name the original file that is stored on disk with the `usingFileName`-function.

See http://medialibrary.spatie.be/v3/api/adding-files/

**Comment by alexglue** [comment]
@cviebrock Ok, nice. and could you tell me what Custom Path Generator do you use actually?
Let me explain you what i mean:
1) You upload first file, and it stored to /62/93/62933a2951ef01f4eafd9bdf4d3cd2f0/file.jpg
2) Conversions stored as /62/93/62933a2951ef01f4eafd9bdf4d3cd2f0/c/thumb.jpg
3) Some time later you want to upload another one, and (surprise!) you've got a collision!
file stores as /62/93/62933a2951ef01f4eafd9bdf4d3cd2f0/file2.jpg,
BUT all conversions stores as /62/93/62933a2951ef01f4eafd9bdf4d3cd2f0/c/thumb.jpg, like in (2).

What would you do with it?

```
	public function getPath(Media $media)
	{
		return implode(DIRECTORY_SEPARATOR, array_slice(str_split(md5($media->getKey()), 2), 0, 2)) . DIRECTORY_SEPARATOR . md5($media->getKey()) .  DIRECTORY_SEPARATOR;
	}

	public function getPathForConversions(Media $media)
	{
		return implode(DIRECTORY_SEPARATOR, [$this->getPath($media), 'c' . DIRECTORY_SEPARATOR]);
	}
```

**Comment by freekmurze** [comment]
If you don't use a custom path generator the medialibrary guaranties that there are no filename collisions 

if you do using a custom path generator it's your responsibility to make sure a media item gets it's own unique directory. This is [mentioned in the docs](http://medialibrary.spatie.be/v3/advanced-usage/using-a-custom-directory-structure/)

**Pull request merged**
