### PR TITLE
Add Additional FIlename Sanitization Rules

### PR DESCRIPTION
**Pull request by patinthehat**
This is an update to #3031 as the original author was unable to complete the requirements for the PR, but the credit for this functionality belongs to @tommica, the original author.

This PR updates the #3031 PR functionality to include unit tests.

Original description:

Update the default filename sanitizer to handle funky whitespace characters in files - I had a case where a file was being uploaded, and it kepts throwing Flysystems `CorruptedPathDetected` exception. Not sure if copy-pasting the filename to github keeps the characters there: `Scan-‎9‎.‎14‎.‎2022-‎7‎.‎23‎.‎28.pdf`

Screenshot 2022-09-14 at 08 57 37

### CODE REVIEW

**Comment by patinthehat** [comment]
@freekmurze, would you review this PR for acceptance/rejection when you have a minute? See #3031 for the original PR without unit tests. Thanks!

**Comment by freekmurze** [comment]
It is kinda hard to review this PR as there are many unrelated changes. Could you update this PR (or create a new one) with only the relevant changes?

**Comment by patinthehat** [comment]
Whoops, nice catch - oversight on my part.  I'll update it accordingly, stand by.

**Comment by patinthehat** [comment]
closing in favor of #3105.

**Pull request closed without merging**
