### PR TITLE
Add ability to save media without a model relationship

### PR DESCRIPTION
**Pull request by jlmmns**
## Usage

```
$media = Media::add($pathToFile)->toMediaCollection('images');
```

```
$media = Media::addFromRequest('image')->toMediaCollection('images');
```

### CODE REVIEW

**Comment by lingotacro** [comment]
how can update medias ?

**Comment by jlmmns** [comment]
@lingotacro Is your question related to this pull request, because of an error?
If not, it seems like you're asking a general question about this package, or even [updating eloquent models](https://laravel.com/docs/5.8/eloquent#inserting-and-updating-models). There are help forums for such questions.

**Comment by mdixon18** [comment]
I love this. Simply allows you to use this package as a standard library, model lead or both 👍

**Comment by royduin** [comment]
Cool, love to see this merged 💯

**Comment by Triztan** [comment]
It's a good option for a "ajax uploader", so you can first store the file give the ID back and then link it once you save the model(like a Post or something just before actually saving the Post)

**Comment by vortechron** [comment]
i really need this! sometimes i just want to ajax the file first then relink with my model later.

**Comment by brendt** [comment]
@jlmmns since you've made changes to the original migration files, do you think there's a way to add this feature as a non-breaking change?

**Comment by jlmmns** [comment]
@brendt Sorry for the delay.

For a non-breaking change, I guess it's best to create a separate migration for this.

But I see where you think it's still considered a breaking change as long as people have to run `php artisan migrate`.

For a new major release, you could of course then merge the migrations.

**Comment by brendt** [comment]
For now I'll add the "revisit for next major version" label. It will probably won't be too long before we're going to tag it. When doing so, we'll also merge this PR

**Comment by jlmmns** [comment]
Awesome, brendt! 😎

**Comment by amousavii** [comment]
When do you Merge this commit ?

**Comment by brendt** [comment]
@amousavii when we're tagging a new major release. There's no fixed deadline, though it will probably be somewhere with the new Laravel release or PHP 7.4

**Comment by freekmurze** [comment]
Closing for now, but we'll revisit this when creating a new major version.

**Comment by garlian** [comment]
Any chance to merge this feature? I think many are eagerly waiting for this, including me 😄👍 If not possible right now is there a nice workaround to use this without relying on a dummy file model?

**Comment by shortcodes** [comment]
Agree with @garlian . Laravel 6 was released. So according to your previous statement it should be merged by now.

**Comment by freekmurze** [comment]
Laravel 6 will be released next thursday. We'll tag a new version shortly after.

**Comment by shortcodes** [comment]
So will it be merged now/?

**Comment by freekmurze** [comment]
We'll take a look at this PR when we create a new major version of the package.

**Comment by mohammad76** [comment]
please merge this , it's good way to create media

**Comment by yevhenlisovenko** [comment]
Any updates here?

**Comment by shortcodes** [comment]
> Any updates here?

@yevhenlisovenko I quit waiting and created my own solution https://github.com/shortcodes/media

**Comment by freekmurze** [comment]
I have considered this functionality, and have decided not to merge this in, in favour of keeping the package simple.

I think the majority of users associates media with models.

**Comment by shortcodes** [comment]
> I have considered this functionality, and have decided not to merge this in, in favour of keeping the package simple.
> 
> I think the majority of users associates media with models.

I have to disagree. Its very useful when using async requests. For example -  you can't post multipart content and json content at once. There should be possibility to associate it with model but should be also possibility to pin it to the bag.  Anyway I think this is good package and i improved it (including this functionality) by myself at https://github.com/shortcodes/media

**Comment by Vendin** [comment]
@freekmurze what with this necessary functionality for many people ?

**Comment by shirshak55** [comment]
"I have considered this functionality, and have decided not to merge this in, in favour of keeping the package simple."

Disagree hardly. 

We cannot even upload image using ajax without this (without doing some sort of nasty hacks).

**Comment by lukio3** [comment]
I would advise simply making your own Upload model... you will most likely come across columns that you want on the temp model e.g. user_id / team_id that may be unique to your needs anyway.

**Comment by shankhadevpadam** [comment]
Is there any possibility to add this feature in the future ?

**Comment by it4need** [comment]
@freekmurze We also need this feature, because we have some kind of json-fields where we need to associate files without specific models. I think this should be mandatory feature of this package to use it standalone without requiring a specific model.

**Comment by lukio3** [comment]
@it4need

You can define your own model and add your project specific json metadata to it, check out the docs:

https://spatie.be/docs/laravel-medialibrary/v9/advanced-usage/using-your-own-model

**Comment by christopherarter** [comment]
I'll +1 having this would be an excellent feature. It would make this package more of a defacto upload management vs just media galleries.

**Comment by freekmurze** [comment]
I don't have a need for this, so I'm not going to invest my time. 

If somebody want to take a stab at this, feel free to send a new PR. Keep these things in mind:
- only make the minimal amount of changes needed in the PR. Unrelated changes should be sent in another PR
- include tests that prove the new functionality works
- update the docs, so users know how to use the functionality
- small breaking changes (like an updated migration) are allow, but all current tests should pass.


If such a PR comes in, I'll review it and I'll consider merging it in.

**Comment by divdax** [comment]
+1 to store media without a model.

Currently i have an unnecessary `App\File` Model to store (tmp) files. But it does its job job.

**Comment by Kadrian** [comment]
Say you have a blog with a resource "posts". A post has images (for a gallery). Now you're building the "new post" form.

The way to go (also according to this https://stackoverflow.com/questions/33279153/rest-api-file-ie-images-processing-best-practices) would be 
- to upload images (without a model), as soon as the user selects one. You store the media / image ids
- then you `POST /post` the json for the new blog post and then `PATCH /post/<id>` with all of the now associated images, which would get assigned to the model now.
- In case images were uploaded that are left without a model, you can clean those up with a cronjob periodically

=> A way to add images to some kind of global library / collection and to be able to then re-assign those to models totally makes sense in my opinion.

**Comment by yassinya** [comment]
This is really a much needed functionality @freekmurze!

_Proceeds to create a second unnecessary model_

**Comment by vrusua** [comment]
@freekmurze Hi Freek, it's so actively voted request during last 3 years, any chance to reconsider your opinion? This feature can really simplify the life during making SPA and JSON API, then applying hacks every time with own temporarily models. Thanks!

**Comment by Forsakenrox** [comment]
The similar functionality exist in the pro version. that is all you need to know.

**Comment by adampatterson** [comment]
I am struggling to integrate Editor.js with the Media Library for this exact reason. I don't have a model created yet.

I suppose I could make a post image model or something and just add to that and once the post is created see if I can move the image data to the correct model.

**Comment by brendt** [comment]
Because people seem to keep commenting here: we've been using this implementation on spatie.be for 2 years now, it's super easy and simple to add: https://github.com/spatie/spatie.be/blob/main/app/Models/Image.php

**Comment by Forsakenrox** [comment]
@adampatterson i find a way - do not use temporaryUrl() function, upload image in library directly instead, but bind it not to post model, but to uploader user and additional define specified collection name, as example - temp-posts-new\temp-posts-{post_id}. After page reloading just clear all user library by user model and collection name "temp-*" and ahwen you want to save your post just update your media models and set post model as correct relation

**Comment by adampatterson** [comment]
> @adampatterson i find a way - do not use temporaryUrl() function, upload image in library directly instead, but bind it not to post model, but to uploader user and additional define specified collection name, as example - temp-posts-new\temp-posts-{post_id}. After page reloading just clear all user library by user model and collection name "temp-*" and when you want to save your post just update your media models and set post model as correct relation

I created a new model called PostMedia where I have a nullable `post_id`. I then create a new record ( nothing in it but an ID ) then upload the image.

My plan now is on save to look for the `id` of `PostMedia` then update the entry with the `$post->id`.

I hope to be able to also clean up images that are uploaded but never saved to a post.

**Comment by johncarter-** [comment]
> The similar functionality exist in the pro version. that is all you need to know.

Can this be done in Pro? I can't see any reference to it 🤔 I'd happily pay for this.

**Comment by adampatterson** [comment]
> > @adampatterson i find a way - do not use temporaryUrl() function, upload image in library directly instead, but bind it not to post model, but to uploader user and additional define specified collection name, as example - temp-posts-new\temp-posts-{post_id}. After page reloading just clear all user library by user model and collection name "temp-*" and when you want to save your post just update your media models and set post model as correct relation
> 
> I created a new model called PostMedia where I have a nullable `post_id`. I then create a new record ( nothing in it but an ID ) then upload the image.
> 
> My plan now is on save to look for the `id` of `PostMedia` then update the entry with the `$post->id`.
> 
> I hope to be able to also clean up images that are uploaded but never saved to a post.

This method worked like a charm.

**Comment by mrbuku** [comment]
if anyone is still struggling with this issue, have a look at this tutorial [](https://www.youtube.com/watch?v=GRXaCfS1qj0) . it's nice workaround.

**Comment by titantwentyone** [comment]
I came across this obviosuly looking for some kind od solution.

A ot of the requests for this change are related to the handling of uploading images. However in terms of data, one thing I wanted to point out is that for some media, it would be illogical to bind it to a particular model. Consider a company logo, for example being used in a CMS. This could be used in a variety of different areas. We want it in the media library but not tied to any particular entitiy.

**Comment by adampatterson** [comment]
@titantwentyone the way I have been handling Media is to make use of a specific media model.

Since I am using it mainly for posts. There are many times when a post has not been saved yet.

So when I upload an image it heads to an endpoint, does its business, and then returns a Media ID.

I save that media response in my post and when the post is actually saved I create the post and then I look for in my Media model for the reference ID and then add the post ID to keep the relations working through my Post model.

The default Spati `media` table is used and holds the relations to my `post_media`  but now I don't need to worry about creating an empty post record at the time of image upload which is likely before the post has been created.

The downside is that if the images are uploaded and the post is never saved you would need to come up with a rule to clear out those detached images.

**Comment by titantwentyone** [comment]
Thanks @adampatterson. Yeh. I've been thinking along these lines. Bind the image to an Image model rather than, say, a Post model. This might be a better way actually as you could go further and handle groups of related image sizes such as 'thumbnail' etc by creating a relationship grouping these images together without polluting "name" or "collection" fields (e.g "variants"). Also allows me not to have any association with a model if it's not appropriate. An intermediary is the way I think.

**Comment by kamasuPaul** [comment]
Has this been merged?.

**Comment by acenkus** [comment]
Why is everybody ignoring this issue?

For example, now I decided to use this package. But I need media files not associated with other modules and saved in the media table. 
I need functionality to associate media items with models after their upload.

That's small fix.

Come one, guys. You are selling this product...

**Comment by shortcodes** [comment]
@acenkus They have a paid version of this library to achieve what you want. If you do not want use it you can use a public wrapper i created https://github.com/mindz-team/laravel-media

**Comment by acenkus** [comment]
@shortcodes I tried it, but documentation of usage was too difficult to understand, sorry.

So I choose this one: [https://github.com/optixsolutions/laravel-media](url)

**Comment by kossa** [comment]
I have the same needs, after taking the time to read the code, I found a solution(or a hack ^^):
1. Update your migration from `$table->morphs('model');` to `$table->nullableMorphs('model');`
2. To bypass this part of [code](https://github.com/spatie/laravel-medialibrary/blob/main/src/MediaCollections/FileAdder.php#L413-L425) create an instance of any model and set exists to `true` something like this:
```php
$post = new Post;
$post->exists = true; // Very important
$post->copyMedia(public_path('images/logo.png')) // copyMedia, addMedia or any associating function
                    ->toMediaCollection('images', 'public');
``` 

Bingo!!!  here is the result:

image



May be this is not the best solution but it works fine

**Comment by adampatterson** [comment]
@kossa I also used the nullable morphs and feel bad for not updating this post.

I create my `PostMedia` when uploading from the WYSIWYG editor returning a media ID back to the editor, when you save the content I create the `Post` and then look for an image block, grab the media ID and update the `PostMedia` with the new post ID.

```php
foreach ($blockContent as $block) {
    if ($block->type === "image") {
        $postMedia = PostMedia::find($block->data->file->postMediaId);
        $postMedia->post_id = $postId;
        $postMedia->save();
    }
}
```

The key is clearly the `$table->nullableMorphs('model');`

**Comment by adampatterson** [comment]
@kossa for me in my app, I have people who can write posts in different profiles. There is a Post Media model that images are attached to on upload. They are not directly attached to the post ID.  I wanted an easy way to get all of the users images without needing to go **user -> post -> images**

So when the post is created the post ID is added to post media.

But I think if you want to attach to the post directly your method is probably ideal as long as copy doesn't make a copy of the image. 

In mine I don't move the image.

**Comment by kossa** [comment]
In your case you can just use [custom properties](https://spatie.be/docs/laravel-medialibrary/v10/advanced-usage/using-custom-properties) something like ['user_id' => 1], then you can search by json using where('custom_properties->user_id', 1)

**Comment by Forsakenrox** [comment]
> I have the same need, after taking the time to read the code, I found a solution(or a hack ^^):
> 
> 1. Update your migration from `$table->morphs('model');` to `$table->nullableMorphs('model');`
> 2. To bypass this part of [code](https://github.com/spatie/laravel-medialibrary/blob/main/src/MediaCollections/FileAdder.php#L413-L425) create an instance of any model and set exists to `true` something like this:
> 
> ```
> $post = new Post;
> $post->exists = true; // VERY IMPORTANT
> $post->copyMedia(public_path('images/logo.png')) // copyMedia, addMedia or any associating function
>                     ->toMediaCollection('images');
> ```
> 
> Bingo!!! here is the result:
> 
> image
> 
> May be this is not the best solution but it works fine

I make own model that implement original Media and a little modify your suggestion:
```php
$media new Media();
$media->exists = true;
Media::addMedia($file)->toMediaCollection();
```
Of course i was modify migration to nullableMorphs().

All magic was in "exists" property.
Thx you, very appreciate.

**Comment by kossa** [comment]
You're welcome

**Comment by saeedvir** [comment]
you can use this :

https://gist.github.com/saeedvir/968ec62b1cfc33a1cbab8e07178a25c1

**Comment by Taosif7** [comment]
Hey @freekmurze, any developments on this?

**Pull request closed without merging**
