### PR TITLE
Add fallback path/url support for conversions

### PR DESCRIPTION
**Pull request by mertasan**
```php
$this->addMediaCollection('avatar')
     ->useFallbackUrl('/default-avatar.jpg')
     ->useFallbackUrl('/default-avatar-50x50.jpg', 'avatar_thumb');

```

```php
$this->addMediaConversion('avatar_thumb')
     ->width(50)
     ->height(50);
```

```php
$model->getFirstMediaUrl('avatar'); // default-avatar.jpg

$model->getFirstMediaUrl('avatar', 'avatar_thumb'); // default-avatar-50x50.jpg

$model->getFirstMediaUrl('avatar', 'foo'); // default-avatar.jpg
```

---

```php
$this->addMediaCollection('seo_images')
     ->useFallbackUrl('/default-1920x1080.jpg')
     ->useFallbackUrl('/default-twitter-1200x600.jpg', 'twitter')
     ->useFallbackUrl('/default-open-graph-1200x630.jpg', 'open_graph');

```

```php
$this->addMediaConversion('twitter')
     ->width(1200)
     ->height(600);

$this->addMediaConversion('open_graph')
     ->width(1200)
     ->height(630);
```

```php
$model->getFirstMediaUrl('seo_images'); // default-1920x1080.jpg

$model->getFirstMediaUrl('seo_images', 'twitter'); // default-twitter-1200x600.jpg

$model->getFirstMediaUrl('seo_images', 'open_graph'); // default-open-graph-1200x630.jpg

```

### CODE REVIEW

**Comment by freekmurze** [comment]
Very nice, could you also update the docs with a few examples?

**Comment by mertasan** [comment]
Sure, Freek. Thank you.

**Comment by mertasan** [comment]
Done. Ready to merge. @freekmurze

**Comment by freekmurze** [comment]
Thank you!

**Pull request merged**
