### PR TITLE
Default file system config key format changed to the snake_case

### PR DESCRIPTION
**Pull request by ModernArtisan**
```defaultFilesystem``` key changed to ```default_filesystem```, for uniformity all of config keys.

### CODE REVIEW

**Comment by sebastiandedeyne** [comment]
This is necessary at some point, but it's a breaking change so I'm afraid we can't pull this in yet :/

**Comment by ModernArtisan** [comment]
I have found only 2 calls of this value. Don't see cases which will break any functionality.

**Comment by sebastiandedeyne** [comment]
It would break the package for users that have published the config file and set a different value for `defaultFilesystem`.

**Comment by freekmurze** [comment]
It's breaking for people who have published their config file and upgrade their package. We'll fix this in the next major version.

**Comment by ModernArtisan** [comment]
Yep, it's for next major release. With updated upgrade guide.

**Comment by freekmurze** [comment]
This has been done in the `laravel55` branch.

**Pull request closed without merging**
