### PR TITLE
Responsable

### PR DESCRIPTION
**Pull request by bmichotte**
This PR implements the `Illuminate\Contracts\Support\Responsable` interface in the `Media` model.

This allows us to do some stuff like this
```php
Route::get('/some/secret/path/{id}', 'SomeController@secret_download')
        ->middleware(['auth', 
            'role:super_secret_role',
            'permission:can download secret images'
         ]); 

class SomeController 
{
  public function secret_download($id)
  {
        return Media::findOrFail($id);
  }
}
```

Tests provided (image and text file)

### CODE REVIEW

**Comment by freekmurze** [comment]
Pretty cool stuff man!

Could you also send a PR to the docs repo?

**Comment by bmichotte** [comment]
Sure, but I'm not sure on which page of the doc I should add it

**Comment by freekmurze** [comment]
Create a new page "Responding with media" in the "Advanced usage" section.

**Comment by freekmurze** [comment]
Thanks a lot for this!

**Pull request merged**
