### PR TITLE
#3015 - Add test for single file collections not working properly when copying media from another model.

### PR DESCRIPTION
**Pull request by victor-priceputu**
Added test to replicate issue presented in https://github.com/spatie/laravel-medialibrary/issues/3015

### CODE REVIEW

**Comment by freekmurze** [comment]
That is indeed failing, could you also add the fix to this PR?

**Comment by victor-priceputu** [comment]
I will try to make an efficient fix. I am thinking of checking if we can take the max from the already-loaded media collection (if possible) and in case we cannot, to make the DB call for the sort, to try and find an optimal solution.

will have to make some local testing with bigger collections to see which way is better rounded for more cases when it comes to the amount of data

**Comment by patinthehat** [comment]
@victor-priceputu Are you still able to work on adding a fix for this issue? If you don't have time right now no problem - I can look into implementing a fix in a separate PR if necessary.  Thanks!

**Comment by victor-priceputu** [comment]
@patinthehat unfortunately the quickest I can work on it properly is in one month.
I just updated my fork and I cannot make the fix in just a few minutes I have available at the moment (there are some tests failing for me and I have to check them out as well)

**Comment by patinthehat** [comment]
@victor-priceputu Thanks for the update.  Please post a comment once you've submitted a PR or let us know if you don't have time and we'll create an issue for this that someone else can pick up. Thanks!

**Comment by victor-priceputu** [comment]
Hey, I tried to do this over the holiday but had no time, and do not see any spare time any time soon. If anyone wants to pick this up, please feel free to do so with my thanks

**Comment by freekmurze** [comment]
Closing due to inactivity.

**Pull request closed without merging**
