### PR TITLE
Added instructions to use the trait

### PR DESCRIPTION
**Pull request by LasseRafn**
The readme did not mention the trait. The text could OBVIOUSLY need some changes but.. yeah. At least this is a start. Hopefully I eased the job a little bit 👍

### CODE REVIEW

**Comment by freekmurze** [comment]
Hi,

thank you for this. I'm not going to merge this in as the detailed instructions on how to use the package are available on [our documentation site](https://docs.spatie.be/laravel-medialibrary).

**Comment by LasseRafn** [comment]
This makes sense - I didn't even notice the documentation site, lol. No problem

**Comment by nicolasbeauvais** [comment]
@freekmurze maybe you could put the official documentation site in the GitHub description instead of the v4 announcement ? At first I had some trouble finding the documentation site because of this. 
screenshot-2016-11-08_15-10-11
Or maybe just a bigger link in the readme

**Comment by freekmurze** [comment]
@nicolasbeauvais good suggestions. Done!

**Pull request closed without merging**
