### PR TITLE
Add getLastMedia, getLastMediaUrl, getLastTemporaryUrl, getLastMediaPath methods

### PR DESCRIPTION
**Pull request by kidii**
After that, it would not only be getFirstXY, but also getLastXY methods.

### CODE REVIEW

**Comment by aabadawy** [comment]
Nice Work!, Check this PR also https://github.com/spatie/laravel-medialibrary/pull/3371

**Comment by kidii** [comment]
Oh, I didn't searched for it. :(

Let's see what happens now.😬

**Comment by aabadawy** [comment]
> Oh, I didn't searched for it. :(
> 
> Let's see what happens now.😬

I still see the idea of adding getLastMedia is so helpful 🤝 , as many cases need to fetch the last media, like CV,Profile picture, invoice, ...etc. let's see @freekmurze opinion.

**Comment by freekmurze** [comment]
I'm going to hold off this one for now to keep the package simple.

**Pull request closed without merging**
