### PR TITLE
Add command "medialibrary:clear"

### PR DESCRIPTION
**Pull request by Maxeee09**
Add a command to delete "medias"

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks for contributing!

I like the new functionality and will review the code in detail in the coming days.

**Comment by freekmurze** [comment]
I only got one big remark: The `delete_model_and_collection_medias` should also prove that media in other collections will still exist after calling the command.

**Comment by Maxeee09** [comment]
Yes @freekmurze, this is what I've done. In the `delete_model_and_collection_medias` test, first I check that `media` still exists after calling `medialibrary:clear` command with the `collection1` collection name (which is not the associated collection name). And then, I check that `media` does not exists after calling `medialibrary:clear` command with the `collection` collection name (which is the associated collection name). I agree that used names are disturbing :)

**Comment by freekmurze** [comment]
Ah I see, didn't read it right the first time. All ok then!

**Comment by freekmurze** [comment]
I'll fix some very small nitpicks later tonight (at the latest tomorrow) and tag a new version.

**Comment by Maxeee09** [comment]
@freekmurze No problems :)

**Comment by freekmurze** [comment]
I refactored the command and the tests a bit an tagged a new version `3.15`. 🎉

In your changes there was a bug present that could lead to data loss. If only `collectionName` was specified when running the command, all media would be deleted.

**Comment by Maxeee09** [comment]
🎉

**Pull request merged**
