### PR TITLE
Add Laravel 5.8 support

### PR DESCRIPTION
**Pull request by lloricode**

### CODE REVIEW

**Comment by jhm-ciberman** [comment]
The test for php 7.2 is failing. 
It seems you also need to update `"orchestra/testbench": "~3.5.0|~3.6.0|~3.7.0|~3.8.0",`

**Comment by lloricode** [comment]
i think this is done from owner

**Comment by jhm-ciberman** [comment]
> hink this is done from owner

What do you mean by "is done from owner"? Did ´laravel-medialibrary´ get updated to L5.8 already?

**Comment by jhm-ciberman** [comment]
O yes. Just saw the commit.

**Pull request closed without merging**
