### PR TITLE
Checking path before Finfo

### PR DESCRIPTION
**Pull request by taliptako**
Sometimes i can add media without file

### CODE REVIEW

**Comment by taliptako** [comment]
I can fix styleci error if you accept this pull patch

**Comment by freekmurze** [comment]
What's your use case for this change?

**Comment by taliptako** [comment]
I'm trying to create media  and my media also have title and desc fields.When user create media without file just with title and desc i'm creating media like this $post->media()->create($fields); and i'm just getting error from Finfo i dont understand why because i'm not adding it from $post->addMedia();

**Comment by freekmurze** [comment]
Imo a Media object should always have a valid file.

To avoid the usage `Finfo` in your project you could use a custom `Media` model overriding any function that are causing your troubles.

**Pull request closed without merging**
