### PR TITLE
add feature: getLastMedia

### PR DESCRIPTION
**Pull request by aabadawy**
As the `getFirstMedia` feature is popular to use in many cases, I think also one of the most popular cases to retrieve the **last media.** 
for example: 
- Get the profile picture.
- Get the uploaded CV.
- Get the project proposal doc .
- I think in the previous examples, usually the default media is the **last** one, not the first **one**.
so I had added `getLastMedia`, `getLastMediaUrl`, `getLastMediaPath`, and `getLastMediaTemporaryUrl`.

### CODE REVIEW

**Comment by freekmurze** [comment]
To keep the package simple, I'm going to hold off on this one for now.

**Comment by ssheduardo** [comment]
But is there any way to get the last item added to a collection?
When I upload an image I want to return the information of the uploaded item, how can I do it?

**Comment by aabadawy** [comment]
@ssheduardo, after uploading media using `toMediaCollection()` method this return the uploaded media model, which you can use, to access the media information. 

Also, you can retrieve the **last** uploaded media attached with your model like this, 
`$lastMedia = $yourModel->getMedia()->last()`
This will return the last media item in the media collection

**Comment by ssheduardo** [comment]
> @ssheduardo, after uploading media using `toMediaCollection()` method this return the uploaded media model, which you can use, to access the media information.
> 
> Also, you can retrieve the **last** uploaded media attached with your model like this, `$lastMedia = $yourModel->getMedia()->last()` This will return the last media item in the media collection

Thanks for your information, yesterday I was try this and work nice.

**Comment by aabadawy** [comment]
> > @ssheduardo, after uploading media using `toMediaCollection()` method this return the uploaded media model, which you can use, to access the media information.
> > Also, you can retrieve the **last** uploaded media attached with your model like this, `$lastMedia = $yourModel->getMedia()->last()` This will return the last media item in the media collection
> 
> Thanks for your information, yesterday I was try this and work nice.

You are welcome @ssheduardo, Happy to hear that 😄

**Comment by richt222** [comment]
@freekmurze, just adding - I think this is a good contribution that would make a lot of sense. Given there's a "getFirst", a "getLast" counterpart seems a logical addition.

Retrieving the last added media would serve a lot of common use cases, as @aabadawy describes. Probably even more so than getFirst.

Might be worth considering again.

**Pull request closed without merging**
