### PR TITLE
Use travis build id to separate s3 test files

### PR DESCRIPTION
**Pull request by nicolasbeauvais**

### CODE REVIEW

**Comment by nicolasbeauvais** [comment]
Even with access to the repo I cannot read Travis's env vars :/

**Comment by freekmurze** [comment]
Thanks, if you pass along your e-mailadress I'll just mail you the credentials of the bucket so you can run the tests locally on your computer. Of course take care that you don't commit the values to the repo.

**Comment by nicolasbeauvais** [comment]
It's ok I already have my own test bucket, I will setup travis on my fork :)

**Comment by freekmurze** [comment]
👍

**Pull request merged**
