### PR TITLE
Fix responsive url generation

### LINKED ISSUE #2778: Responsive images of a conversion from a collection changed in v10?
I've upgraded an application to L9 and Media Library 10 however the responsive images seem to be behave differently and are giving me an exception:

I have a blade component for a card which I pass in a video:

```blade
@php
    $thumbnail = $video->getFirstMedia('thumbnail');
@endphp

<div class="relative group">
    <div class="overflow-hidden w-full bg-gray-200 rounded-md shadow-md aspect-video group-hover:opacity-75">
        <div class="relative">

            <a href="{{ route('video.show', $video->id) }}">
                @if($thumbnail)
                    {{ $thumbnail('app-thumbnail') }}
                @else
                    <img src="{{ asset('images/video.png') }}" alt="Video Thumbnail">
                @endif
            </a>

<snip...>
```

This gets the first media from a collection called thumbnail and then should display the responsive images for the app-thumbnail conversion, worked fine on Laravel 8 and ML 9 however I now get

`Found 1 error while validating the input provided for the GetObject operation: [Key] expected string length to be >= 1, but found string length of 0`

I've dumped `$thumbnail` and can see the conversion available there.
Screenshot 2022-02-14 at 11 21 44

Has something changed with ML10 that I need to be aware of?

### PR DESCRIPTION
**Pull request by mabdullahsari**
This is a duplicate of #2837 that fixes the issue for v10.

Closes #2778.

### CODE REVIEW

**Comment by mabdullahsari** [comment]
@freekmurze Hey 👋🏼

I think the tests need updating, am I right? I tested it locally on an app that relies heavily on media-library, and everything seems to be working fine with the S3 disk.

The localhost portion is probably omitted everywhere because it is the local disk, and thus does not really require an absolute URL.

How do I proceed?

**Comment by freekmurze** [comment]
The tests indeed need updating. If you want, go ahead and already do that. If not I'll update them later this week.

**Comment by mabdullahsari** [comment]
> The tests indeed need updating. If you want, go ahead and already do that. If not I'll update them later this week.

I'll update them no problems. Just wanted to make sure. Thanks!

**Comment by mabdullahsari** [comment]
I guess all of the code analysis failures are unrelated to my changes.

**Comment by freekmurze** [comment]
Yeah, I'll fix those myself, no worries!

**Comment by freekmurze** [comment]
Thank you!

**Comment by mabdullahsari** [comment]
> Thank you!

Tyvm for merging 🙏

Could you release this as a patch please? 😇

**Comment by ricardo-lobo** [comment]
Can this be merged into v10 too?

**Comment by freekmurze** [comment]
done!




Freek Van der Herten
https://spatie.be

**Pull request merged**
