### PR TITLE
Update the migration stub to include dropIfExists clause

### PR DESCRIPTION
**Pull request by nexxai**
There was no dropIfExists clause in the stub so I've added one here.

### CODE REVIEW

**Comment by freekmurze** [comment]
We don’t migrite down in any of our package or projects.

**Comment by nexxai** [comment]
I’m totally ok with that, I’m just wondering if you can explain why (maybe I shouldn’t be migrating down either?)

**Comment by freekmurze** [comment]
I think 99.9% of the time you are not gonna use a down migration, you’re probably never test them, so why even bother writing them. 

Just write an up migration if you want to drop a column again. 👍

**Comment by nexxai** [comment]
Interesting. Thanks for that perspective, man!

**Pull request closed without merging**
