### PR TITLE
Add fallback path and URL to media collections

### PR DESCRIPTION
**Pull request by jameslkingsley**
I needed this functionality but it doesn't look like #1101 made any progress, so here's a PR for the functionality outlined in that issue.

### CODE REVIEW

**Comment by ArmeniaH** [comment]
bump

**Comment by clemjlt** [comment]
Hi ! What's the status on this one ? It would be pretty useful :)

**Comment by freekmurze** [comment]
Thanks!

**Comment by nelson6e65** [comment]
Hmm... Seems like this only works for `getFirstMediaUrl()` and `getFirstMediaPath()` methoda, but `getFirstMedia()` still returning null. :sweat_smile:

**Comment by freekmurze** [comment]
I don't have time to look into this now, but if you PR a fix with tests, i'll likely merge it.

**Comment by morawcik** [comment]
Any info about default image for getFirstMedia() and getMedia() ? Or any advice how to use default image with responsive images?

**Comment by clemjlt** [comment]
`getFirstMediaUrl()` asks media library for a `Media` using `getMedia()` behind the scenes, and returns the fallback url if `getMedia()` returns `null`. 
Given this, it's impossible to get a default value when you use `getMedia()` because the check to return the default url is implemented after `getMedia()` is called (in `getFirstMediaUrl()`)

A solution to make this work could be to move the check in `getMedia()` instead of `getMediaUrl()`, and use a default media instead of a default Url. But I think it's not in the scope of this PR ...

**Pull request merged**
