### PR TITLE
Add `getMediaRepository()` to `InteractsWithMedia` and `query()` to `MediaRepository`

### PR DESCRIPTION
**Pull request by stevebauman**
**Description**:
This PR adds two new methods:

- The `getMediaRepository()` method so it can be easily retrieved from the model that `InteractsWithMedia`
- The `query()` method, for extensibility over the media repository's query

**Purpose**:
This adds a couple of benefits:

- Easily override the the base query that is created from the `MediaRepository`
- Easily utilize the media repository methods with `HasMedia` models
- The `MediaRepository` can now be extended/overridden *per model*
- IDE auto-completion

Let me know your thoughts! No hard feelings on closure.

Thanks for your time!

### CODE REVIEW

**Comment by freekmurze** [comment]
We will merge this in after the tests have been fixed by #2518

**Comment by stevebauman** [comment]
Awesome, thanks @freekmurze! Appreciate it!

**Comment by freekmurze** [comment]
@stevebauman can you rebase with the main branch, then the tests should all pass.

**Comment by stevebauman** [comment]
Done! 👍

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
