### PR TITLE
added withResponsiveImagesIf() on conversions

### PR DESCRIPTION
**Pull request by rcerljenko**

### CODE REVIEW

**Comment by freekmurze** [comment]
Could you add tests that prove that this works?

**Comment by rcerljenko** [comment]
Ok I'll try (I don't have that much experience in writing tests)  :)

**Comment by sebastiandedeyne** [comment]
Why not change the signature of `withResponsiveImages()` to `withResponsiveImages(bool $withResponsiveImages = true)` instead? That way we don't have to add a new method to the API.

**Comment by rcerljenko** [comment]
@sebastiandedeyne because that was already discussed in the simmilar PR here https://github.com/spatie/laravel-medialibrary/pull/2036

**Comment by sebastiandedeyne** [comment]
I wasn't aware of that, carry on 😅

**Comment by freekmurze** [comment]
Tests seem to fail, could you take a look at that?

**Comment by rcerljenko** [comment]
@freekmurze hi i'm looking it but i think it's not related to my part of the code
maybe i'm wrong but it fails in a completly weird place

**Comment by freekmurze** [comment]
Could you rebase this to the master branch? With any luck we don't get any failing tests after that.

**Pull request closed without merging**
