### PR TITLE
Fix wrong deletions

### PR DESCRIPTION
**Pull request by inalto**
In case of custom paths setup to save the images in the same subdirectory ex. username/post_id/photos/somefile.ext when a file is removed from the media directory it wipes all the directory content.

This commit fixes this problem only deleting the proper images (and related conversions and responsive images) and delete the directory only if is empty.

### CODE REVIEW

**Comment by freekmurze** [comment]
Hi, could you also add a test to prove that this works?

**Comment by inalto** [comment]
yes, I write one

**Comment by inalto** [comment]
hello, i added some test and spotted some bugs on DefaultFileRemover, now i look at failing tests

**Comment by inalto** [comment]
Problem in case of custom-named media is fixed now. And all the test are passing, included new ones.

**Comment by freekmurze** [comment]
Thank you very much!

**Pull request merged**
