### PR TITLE
change return type of getMedia()

### PR DESCRIPTION
**Pull request by Danger-Mkh**
change return type from Colllection to MediaCollections\Models\Collections\MediaCollection
because InteractsWithMedia trait not the same as HasMedia interface

### CODE REVIEW

**Comment by freekmurze** [comment]
In rare circumstances, where people have override certain methods, narrowing the return type could be a breaking change.

As this change doesn't solve a real problem, I'm going to skip this for now.

Thanks for your work on this.

**Comment by AlexanderPoellmann** [comment]
Hi @freekmurze, I don't follow your reply, but maybe I just misunderstand your point.

I too get an error as the method declaration of 'InteractsWithMedia->getMedia()' is not compatible with 'HasMedia->getMedia()', which in fact is a simple `Collection` on the interface while on the trait a `MediaCollection`.

Thanks in advance for some clarification ;-)

**Comment by jonnywilliamson** [comment]
@freekmurze Does this not flag up with a red error on your phpStorm?

image

**Comment by jonnywilliamson** [comment]
For anyone following. I found the mentioned bug track number here:

https://youtrack.jetbrains.com/issue/WI-53288
https://youtrack.jetbrains.com/issue/WI-57097

This package actually gets a specific mention. Hopefully fixed soon.

Thank you @freekmurze . I wasn't implying that your package was broken! Just curious if your system didn't highlight it like mine!

**Comment by AlexanderPoellmann** [comment]
Thanks @freekmurze, and thanks @jonnywilliamson for the links.

**Pull request closed without merging**
