### PR TITLE
Fixing bug #970

### PR DESCRIPTION
**Pull request by IshanDemon**
addMediaFromUrl fail when url is little bit weird.

### CODE REVIEW

**Comment by freekmurze** [comment]
Could you add a test for this?

**Comment by IshanDemon** [comment]
Yes sure. Will do that in few minutes.

**Comment by IshanDemon** [comment]
I have added a test case for same. Also, you may need to update URL for the image.
For now, I am using 
https://dthumb-phinf.pstatic.net/?src=%22https%3A%2F%2Fshop-phinf.pstatic.net%2F20180116_81%2Flovelyamie_1516031621836Wd9JR_JPEG%2F39338801478811043_156275708.jpg%3Ftype%3Dm450%22&amp;type=ff120

Please replicate it to 
https://docs.spatie.be......
and please update branch accordingly.

Please let me know If I am missing something.

**Comment by freekmurze** [comment]
Thanks!

**Comment by IshanDemon** [comment]
My Pleasure.
Thanks for providing all these packages. 
You and your team is doing an awesome job.
:)

**Pull request merged**
